set up for prometheus stack
ray-project/kuberay pull request #230
Opened 2022-04-19 05:07 UTC by scarlet25151

@Jeffwan 

## Why are these changes needed?

This pr will enable the specific prometheus stack for kuberay, including some setting for service monitor and the configurations for the grafana dashboard.

## Related issue number

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

2022-04-20 00:00 UTC, Jeffwan commented
![image](https://user-images.githubusercontent.com/4739316/164120234-58507426-dc49-45c3-a100-89ba0e717f17.png)
![image](https://user-images.githubusercontent.com/4739316/164120278-4eb8216b-7f61-4cf4-9d50-c931e5ce8258.png)
![image](https://user-images.githubusercontent.com/4739316/164120291-660ef6d4-fa98-4212-b81d-507feb21aa09.png)

2022-04-20 02:59 UTC, harryge00 commented
Great PR! I think we should also update docs on how to enable monitoring?

2022-04-20 08:32 UTC, Jeffwan commented
![image](https://user-images.githubusercontent.com/4739316/164186143-ccb303ea-69e3-4117-a885-fcb4b320514f.png)

@scarlet25151 Seems the unit test doesn't pass, please take a look and fix it.

2022-04-20 23:46 UTC, Jeffwan commented
@scarlet25151 can you also address @harryge00's comment? let's add a short doc on the usage.

2022-04-21 20:57 UTC, scarlet25151 commented
Hi @harryge00 @Jeffwan I've address the comments and plz take a look.

2022-04-24 06:26 UTC, harryge00 requested changes
Just two typos

2022-04-24 06:26 UTC, harryge00 commented on README.md
> +We have add a paramaeter `--metrics-expose-port=8080` to open the port and expose metrics both for the ray cluster and our control plane. We also leverage the [Prometheus Operator](https://github.com
typo `parameter`

2022-04-24 06:26 UTC, harryge00 commented on README.md
> +You can quickly deploy one by the following on your on kubernetes cluster by using the scripts in install:
`on your own kubernetes cluster` ?

2022-04-24 06:27 UTC, harryge00 commented
LGTM after fixing typos

2022-04-26 00:06 UTC, Jeffwan approved these changes

2022-04-26 00:06 UTC, merged