Add topology spread constraints test for RayCluster
ray-project/kuberay pull request #2472
Opened 2024-10-24 20:32 UTC by YoussefEssDS

This PR adds a test to verify the functionality of topology spread constraints in a RayCluster setup. The test ensures that worker pods respect the topology spread constraints defined in the cluster's YAML file, particularly focusing on distributing pods across nodes while adhering to maxSkew and avoiding node overloading.
Thanks to @nemo9cby, @liuxsh9, @Superskyyy and @Bye-legumes for the help!

The modifications include:
A new YAML file with topology spread constraints applied to the worker groups.
An update to the e2e test setup to deploy the cluster with the new topology spread configuration.
Validation logic to ensure pods are scheduled according to the specified constraints.

Why are these changes needed?
Topology spread constraints are a Kubernetes feature that helps to distribute pods evenly across nodes to improve high availability and fault tolerance. This test is necessary to ensure that RayCluster configurations support these constraints properly, providing users with greater control over pod scheduling. It helps in scenarios where workload distribution across nodes is critical for resource balancing.

Related issue number
This PR addresses the need for testing topology spread constraints in the KubeRay setup, as requested in a related issue https://github.com/ray-project/kuberay/issues/2273

Checks
I've made sure the tests are passing.
Testing Strategy
Manual tests: Validated topology spread constraint behavior by observing pod distribution in the test cluster + description of pending worker pods.

2024-10-24 20:45 UTC, YoussefEssDS commented
@kevin85421 can you please review this PR?

2024-10-29 05:40 UTC, kevin85421 commented
cc @MortalHappiness would you mind reviewing this PR?

2024-10-29 11:46 UTC, MortalHappiness requested changes
I think this is more like a kind of sample yaml test. So you need to change the following files instead:

- `./tests/framework/config/kind-config-buildkite.yml`: Add more nodes here.
- `ray-operator/test/sampleyaml/raycluster_test.go`: Create a new function named `TestRayClusterTopologySC`. You can reference the implementation of `TestRayCluster` function in the same file.
- Also remember to sync with the master branch

Other related files:

- `.buildkite/test-sample-yamls.yml`

cc @kevin85421 What do you think?

2024-10-29 11:46 UTC, MortalHappiness commented on ray-operator/config/samples/ray-cluster.TopoSpreadConst.yaml
> +apiVersion: ray.io/v1
Rename this file to `ray-cluster.topo-spread-constraints.yaml` to keep it consistent with the naming of other files.

2024-10-29 22:24 UTC, YoussefEssDS commented
@MortalHappiness Thanks for the review. I addressed the suggestions you had. Please let me know if that's what you had in mind.

2024-10-31 06:48 UTC, kevin85421 reviewed
Thank you for the PR!

Testing the behavior of `topologySpreadConstraints` is out of scope for KubeRay. KubeRay only ensures that the user-specified Pod spec is passed to the underlying Ray Pods. Would you mind removing everything instead of the changes under `helm-chart/ray-cluster`?

Instead, can you write more details about how do you manually test this PR in the PR description?

2024-10-31 06:48 UTC, kevin85421 commented on helm-chart/ray-cluster/templates/raycluster-cluster.yaml
> +        topologySpreadConstraints:
1. Is it possible to pass the entire `.Values.head.topologySpreadConstraints` to `topologySpreadConstraints:` if it not empty? If we need to handle the fields one-by-one, we need to update this YAML whenever the `topologySpreadConstraints` APIs add new fields.

2. Don't set any default values.

2024-10-31 18:00 UTC, YoussefEssDS commented
Thanks @kevin85421.  The requested changes are done.

2024-11-05 05:01 UTC, kevin85421 approved these changes

2024-11-05 05:01 UTC, kevin85421 commented
Thank you for the PR!

2024-11-05 05:01 UTC, merged

2024-11-05 05:02 UTC, kevin85421 commented
@YoussefEssDS @Superskyyy sorry for the delay. Feel free to ping me on Ray Slack next time!