[API Server] Add security context to Ray Cluster
ray-project/kuberay pull request #2538
Opened 2024-11-13 08:24 UTC by han-steve

## Why are these changes needed?

Adding the ability to customize the security context for a ray cluster. This is useful for adding necessary permissions to profile a ray cluster. For example, for py-spy to work, we need to add 
```
# `py-spy` is a sampling profiler that requires `SYS_PTRACE` to read process memory effectively.
# Once enabled, you can profile Ray worker processes through Ray Dashboard.
# For more details, refer to:
# https://docs.ray.io/en/latest/ray-observability/user-guides/debug-apps/optimize-performance.html#python-cpu-profiling-in-the-dashboard
securityContext:
  capabilities:
    add:
    - SYS_PTRACE
```
as documented [here](https://docs.ray.io/en/latest/cluster/kubernetes/k8s-ecosystem/pyspy.html). 

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

2024-11-13 17:55 UTC, YQ-Wang requested changes
Left some comments, thanks!

2024-11-13 19:06 UTC, YQ-Wang commented
cc @kevin85421 @andrewsykim

2024-11-14 00:05 UTC, YQ-Wang approved these changes

2024-11-16 07:13 UTC, kevin85421 approved these changes
Yiqing has already approved the PR. Merge.

2024-11-16 07:13 UTC, merged