[kubectl-plugin] Add support for retrieving logs for different ray resource types
ray-project/kuberay pull request #2677
Opened 2024-12-20 22:32 UTC by chiayi

## Why are these changes needed?
Add support for the other ray resources: rayservice and rayjob

## Related issue number
Closes: https://github.com/ray-project/kuberay/issues/2419
Part of: #2608 

## Checks

- [ ] I've made sure the tests are passing.
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

2024-12-20 22:32 UTC, chiayi commented
<img width="1728" alt="Screenshot 2024-12-20 at 2 29 50 PM" src="https://github.com/user-attachments/assets/943a1f62-74a7-4e7c-96da-16bc1cfeea0f" />

2024-12-28 15:14 UTC, MortalHappiness requested changes

2024-12-28 15:14 UTC, MortalHappiness commented on kubectl-plugin/pkg/cmd/log/log.go
> +		Use:               "log (RAYCLUSTER | TYPE/NAME) [--out-dir DIR_PATH] [--node-type all|head|worker]",
L91 should be `completion.RayClusterResourceNameCompletionFunc`

2025-01-02 23:27 UTC, MortalHappiness commented on kubectl-plugin/pkg/cmd/log/log.go
> +	NodeType     string
Why is this variable capitalized? Should we export this variable?

2025-01-06 18:28 UTC, chiayi commented on kubectl-plugin/pkg/cmd/log/log.go
> +		Use:               "log (RAYCLUSTER | TYPE/NAME) [--out-dir DIR_PATH] [--node-type all|head|worker]",
Done!

2025-01-06 22:58 UTC, MortalHappiness approved these changes
LGTM

2025-01-09 03:10 UTC, kevin85421 approved these changes
Stamp. @MortalHappiness has already approved the PR.

2025-01-09 03:11 UTC, merged