feat: Add a new event type FailedToDeleteWorkerPodCollection
ray-project/kuberay pull request #2680
Opened 2024-12-22 07:06 UTC by CheyuWu

## Why are these changes needed?
Currently, we are reusing the FailedToDeleteWorkerPod event type for scenarios where both Delete (requiring the delete verb in Role or ClusterRole) and DeleteAllOf (requiring the deletecollection verb) are involved. However, this reuse may lead to confusion because these operations rely on different verbs and permissions.

To improve clarity and maintainability, we should consider introducing a new event type specific to the DeleteAllOf operation. While it’s not critical to address this issue in the current PR, it can be a good first issue for new contributors to tackle in the future.

## Related issue number

Closes #2672 
## Checks

- [ ] I've made sure the tests are passing.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

2024-12-22 07:13 UTC, CheyuWu commented
@kevin85421  @MortalHappiness  PTAL

2024-12-22 14:02 UTC, MortalHappiness requested changes
Check all places that use `FailedToDeleteWorkerPod`, and change them to `FailedToDeleteWorkerPodCollection` if `DeleteAllOf` is used instead of `Delete`.

2024-12-22 16:46 UTC, CheyuWu commented
@MortalHappiness  I searched for functions related to `r.deleteAllPods`, but I couldn't find anything specifically related to `FailedToDeleteWorkerPod`. However, I did find something related to `FailedToDeletePod` in the `r.deleteAllPods` function. Therefore, I added an additional type, `FailedToDeletePodCollection`.

2024-12-23 04:41 UTC, kevin85421 requested changes
I will review this after #2663 is merged.

2024-12-27 22:49 UTC, kevin85421 commented
@CheyuWu #2663 is merged. You can rebase with the master branch.

2024-12-28 05:30 UTC, CheyuWu commented
@MortalHappiness  @kevin85421 I have checked all of the functions related to `r.deleteAllPods` and changed it to `deleteCollection` type
PTAL

2024-12-28 15:09 UTC, MortalHappiness approved these changes
LGTM

2024-12-29 03:58 UTC, kevin85421 approved these changes

2024-12-29 03:58 UTC, merged