Fix finalizer typo and re-create manifests
ray-project/kuberay pull request #631
Opened 2022-10-12 14:09 UTC by AlessandroPomponio

## Why are these changes needed?

These changes address issue #630

When trying to create one of the example `RayCluster` on OpenShift, it will fail with the operator reporting "cannot set blockOwnerDeletion if an ownerReference refers to a resource you can’t set finalizers on:".

As per https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-, we were able to fix the issue by applying the new `role.yaml` that is created running `make manifests` after applying the changes in this PR. 

## Related issue number

Closes #630 

## Checks

As mentioned, this PR was tested by applying the contents of the `role.yaml` file to the kuberay-operator `ClusterRole` 

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

2022-10-12 16:23 UTC, Jeffwan approved these changes
It is indeed a typo! Thanks for the fix! the change looks good to me

2022-10-12 16:38 UTC, AlessandroPomponio commented
Just a quick double check @Jeffwan - I see the consistency check for the helm chart rbac is failing. Is that supposed to happen due to the changes?
Just to make sure everything is correct.

Thanks a lot in advance.
Alessandro

2022-10-13 00:09 UTC, DmitriGekhtman commented
RBAC files in the Helm charts need to be updated manually.
Specifically, the following file needs the same fix:
https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/templates/role.yaml

Once that's done, you can run `python ../scripts/rbac-check.py` from the root of KubeRay repo to verify that things are correctly synced.
We were unfortunately unable to automate this syncing process.

See https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md#consistency-check

2022-10-13 00:10 UTC, DmitriGekhtman requested changes
Match up Helm roles to get the helm rbac consistency check to pass.

2022-10-13 08:49 UTC, AlessandroPomponio commented
Thank you both @kevin85421 and @DmitriGekhtman for being so kind and pointing me towards the right direction. 

From the docs I had imagined something had to be done but I didn't understand they had to be synchronized manually, I assumed there was an automated process in place (and that I had missed some command). Maybe it could help new users if it was made more explicit in the docs 😃

2022-10-13 17:54 UTC, kevin85421 commented
> Thank you both @kevin85421 and @DmitriGekhtman for being so kind and pointing me towards the right direction.
> 
> From the docs I had imagined something had to be done but I didn't understand they had to be synchronized manually, I assumed there was an automated process in place (and that I had missed some command). Maybe it could help new users if it was made more explicit in the docs 😃

Good idea! I will update the doc. Thank you for pointing this out!

2022-10-13 18:18 UTC, DmitriGekhtman commented
> Thank you both @kevin85421 and @DmitriGekhtman

...I failed to read the comment thread, sorry for the redundant info :)

2022-10-13 18:22 UTC, DmitriGekhtman approved these changes
Thank you!

This is [not the first time](https://github.com/ray-project/kuberay/pull/285/files) we've burned ourselves with singular vs. plural in rbac...

2022-10-13 18:23 UTC, merged