add validation for envs in head start
ray-project/kuberay pull request #636
Opened 2022-10-14 17:55 UTC by scarlet25151

## Why are these changes needed?
We need more validation for the head start params, for example the user may create the ray cluster with some environments, however may forget to added those in the envs in the template, so we may need a validation to check for that.

here it is a little tricky, we only can check the envs added in the template, however when user built the envs in the images, we cannot find that.

## Related issue number

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

2022-10-18 16:50 UTC, Jeffwan requested changes

2022-10-25 23:25 UTC, scarlet25151 commented on ray-operator/controllers/ray/common/pod.go
> +	for _, val := range rayStartParams {
> can we extract this in a validation method?

here we are validating the envs in start params and that's why I put the snippets inside that method, if there is some envs we may recommend user to add it into envs field. 
> This change will fail the cases that env added in container image or injected by webhook
Yes, I feel it's the tricky things, we may not be able to validate the users webhook 

here in this specific case, we may change the status to unhealthy or failed.

2022-11-03 21:22 UTC, DmitriGekhtman commented
@scarlet25151 @Jeffwan 

For ease of tracking, would it be possible to either

- Close this PR.
- Refine it as requested.

If we want to keep this PR and refine it, could you clarify the description, preferably with an example?

2022-12-20 06:45 UTC, DmitriGekhtman commented
Closing as "stale". Obviously, feel free to reopen or open a new PR.

2022-12-20 06:45 UTC, closed without merging