[Feature] Optimize indexer
ray-project/kuberay pull request #996
Opened 2023-03-29 00:24 UTC by kevin85421

## Why are these changes needed?

This PR is used to improve https://github.com/ray-project/kuberay/pull/946. This PR description will discuss the reasons why I make the change and why I do not make the change.

### Indexer
This PR is to optimize indexer (cache) based on kubebuilder's tutorial ([tutorial](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html), [code](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go#L556-L572)). 

## Related issue number

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

2023-03-31 01:05 UTC, kevin85421 commented on ray-operator/controllers/ray/raycluster_controller.go
> +	PodUIDIndexField          = "metadata.uid"
Oops, I forget that. Thank you for pointing this out! By the way, is this PR necessary to be included in the v0.5.0 or it is not that urgent?

2023-03-31 01:08 UTC, kevin85421 commented on ray-operator/controllers/ray/raycluster_controller.go
> +	PodUIDIndexField          = "metadata.uid"
I prefer not to include this in v0.5.0 except this optimization can prevent OOM.

2023-03-31 21:52 UTC, wilsonwang371 commented on ray-operator/controllers/ray/raycluster_controller.go
> +	PodUIDIndexField          = "metadata.uid"
> I prefer not to include this in v0.5.0 except this optimization can prevent OOM.

I am ok with both. This is not a big change.

2023-03-31 21:53 UTC, wilsonwang371 commented on ray-operator/controllers/ray/raycluster_controller.go
> +	PodUIDIndexField          = "metadata.uid"
You can go ahead and make the change and i will give a pass.

2023-04-03 19:20 UTC, wilsonwang371 commented on ray-operator/controllers/ray/raycluster_controller.go
> -
change PodUIDIndexField to podUIDIndexField

2023-04-03 19:21 UTC, wilsonwang371 requested changes
please update the variable and we can merge them after this.

2023-04-03 20:24 UTC, kevin85421 commented
Thank you for the follow-up. I will update this PR after I finish the v0.5.0-rc.0 release process. In addition, this PR will not be included in v0.5.0 because I did not have a chance to benchmark the memory usage.

2023-08-18 20:45 UTC, closed without merging